### PR TITLE
Latest code fixes 

### LINKED ISSUE #6: Fixes as per discoveries in transaction management service
A new PR containing the fixes identified during transaction management service needs to be included with proper test coverage.

Transaction management service: https://github.com/vatsal278/TransactionManagementService

### PR DESCRIPTION
**Pull request by vatsal278**
Fixes issue https://github.com/vatsal278/AccountManagmentSvc/issues/6

### CODE REVIEW

File: internal/middleware/middleware_test.go [hunk 1]
```diff
@@ -659,7 +659,7 @@ func TestUserMgmtMiddleware_Cacher(t *testing.T) {
 				}
 				expected := &model.Response{
 					Status:  http.StatusBadRequest,
-					Message: "1004: unable to assert userid",
+					Message: "2004: unable to assert userid",
```
Comment (PereRohit) [inline internal/middleware/middleware_test.go]: Instead of hardcoding, use the codes.GetErr(codes.ErrAssertUserid) logic to make it dynamic to avoid rework when these are changed.

**Review by PereRohit — APPROVED** [review]
> Proceed to merge after middleware test cases for cacher mocked Set() is implemented instead of gomock.Any().

done

File: coverage [hunk 2]
```diff
@@ -34,48 +34,18 @@ github.com/vatsal278/AccountManagmentSvc/internal/middleware/middleware.go:131.8
 github.com/vatsal278/AccountManagmentSvc/internal/middleware/middleware.go:132.46,133.72 1 1
 github.com/vatsal278/AccountManagmentSvc/internal/middleware/middleware.go:133.72,137.28 4 1
 github.com/vatsal278/AccountManagmentSvc/internal/middleware/middleware.go:146.4,148.18 3 1
-github.com/vatsal278/AccountManagmentSvc/internal/middleware/middleware.go:159.4,162.67 4 1
-github.com/vatsal278/AccountManagmentSvc/internal/middleware/middleware.go:165.4,172.18 3 1
+github.com/vatsal278/AccountManagmentSvc/internal/middleware/middleware.go:159.4,161.67 3 1
```
Comment (PereRohit) [inline coverage]: Remove this from root level.

**Comment by PereRohit** [comment]
> Postman collection name, if updated, must be reflected in the readme also else the link will break. Better to keep the file name same as last time.

done

**Review by PereRohit — APPROVED** [review]

File: internal/middleware/middleware_test.go (hunk 1 above)
Comment (vatsal278) [reply internal/middleware/middleware_test.go]: done

File: coverage (hunk 2 above)
Comment (vatsal278) [reply coverage]: done
